export const allTeamsSummaryResult = [
  {
    id: 1,
    month: "Apr 22",
    summary:
      "It seems that people are feeling a sense of collaboration and teamwork. They appreciate the fact that the work was not done solely by themselves and that there was good communication through Slack.  The constant peer review suggests a culture of feedback and improvement. The approach of dividing and conquering sections of the work indicates efficient task allocation. The mention of learning and development highlights a focus on personal and professional growth. The elevator music during retro suggests a relaxed and enjoyable working environment. The quick delivery of initial dot points implies efficiency and responsiveness. Overall, the team seems open-minded, receptive to feedback, and working together on different sections, creating a positive and collaborative atmosphere.",
    keywords: [
      "Collaboration",
      "Teamwork",
      "Appreciation",
      "Communication",
      "Slack",
      "Peer review",
      "Feedback",
      "Improvement",
      "Task allocation",
      "Learning",
      "Development",
      "Personal",
      "Professional",
      "Environment",
      "Efficiency",
    ],
  },
  {
    id: 2,
    month: "May 22",
    summary:
      "The team demonstrates satisfactory performance, meeting basic expectations but lacking the ability to consistently excel. They exhibit a moderate level of collaboration, but there are occasional breakdowns in communication that hinder their progress. The team's attention to detail is acceptable, but there is room for improvement in terms of consistently delivering high-quality work. Their reactive approach sometimes leaves them struggling to proactively address challenges and seize opportunities. Despite making some efforts towards improvement, the team's performance remains average and fails to stand out from their peers. Overall, there is a need for greater focus, proactive problem-solving, and a stronger drive for excellence in order to elevate the team's performance to a higher level of success.",
    keywords: [
      "Satisfactory",
      "Moderate",
      "Breakdowns",
      "Acceptable",
      "Improvement",
      "Average",
      "Proactive",
      "Challenges",
      "Opportunities",
      "Efforts",
      "Focus",
      "Problem-solving",
      "Drive",
      "Excellence",
      "Success",
    ],
  },
  {
    id: 3,
    month: "Jun 22",
    summary:
      "The team appears to exhibit a moderate level of collaboration and teamwork. They acknowledge the importance of working together and value communication. While they engage in some peer review, there is room for improvement in terms of feedback and fostering a culture of continuous growth. Task allocation seems somewhat efficient with a division of work. They show a slight inclination towards learning and development. The presence of elevator music during retrospectives suggests a relatively relaxed working environment. The team demonstrates a moderate level of efficiency and responsiveness in delivering initial dot points. Overall, they display a certain level of openness and receptiveness to feedback while working on different sections, contributing to a moderately positive and collaborative atmosphere.",
    keywords: [
      "Collaboration",
      "Teamwork",
      "Communication",
      "Peer review",
      "Feedback",
      "Continuous growth",
      "Task allocation",
      "Efficiency",
      "Learning",
      "Development",
      "Relaxed",
      "Environment",
      "Responsiveness",
      "Openness",
      "Receptiveness",
    ],
  },
  {
    id: 4,
    month: "Jul 22",
    summary:
      "The team exemplifies a strong sense of synergy and mutual support, working together seamlessly to achieve their goals. They prioritize effective communication and actively foster an atmosphere of trust and respect. Through their cohesive efforts, they overcome challenges and demonstrate exceptional problem-solving skills. The team's innovative thinking and creative approaches generate fresh perspectives and propel them towards success. They embrace change and adaptability, consistently seeking new opportunities for growth and improvement. The team's dedication to excellence is evident in their meticulous attention to detail and commitment to delivering high-quality outcomes. With their unwavering focus on customer satisfaction, they consistently exceed expectations and maintain strong client relationships. Overall, this team embodies a spirit of innovation, collaboration, and unwavering commitment, making them a force to be reckoned with in their field.",
    keywords: [
      "Synergy",
      "Support",
      "Communication",
      "Trust",
      "Respect",
      "Cohesion",
      "Problem-solving",
      "Innovation",
      "Creativity",
      "Adaptability",
      "Growth",
      "Excellence",
      "Attention to detail",
      "Customer satisfaction",
      "Commitment",
    ],
  },
  {
    id: 5,
    month: "Aug 22",
    summary:
      "The team struggles to foster a cohesive and collaborative environment, often facing communication challenges and a lack of teamwork. Feedback and improvement are often overlooked, resulting in a stagnant culture that inhibits growth. Task allocation is inefficient, leading to delays and subpar productivity. Limited emphasis on learning and development hinders personal and professional growth. The working environment lacks enthusiasm and enjoyment, lacking the necessary elements to foster a positive atmosphere. Timeliness and responsiveness are areas that require improvement, as the team struggles to deliver prompt and efficient results. Overall, the team exhibits a lack of openness and receptiveness to feedback, hindering their ability to work together effectively and create a truly collaborative atmosphere.",
    keywords: [
      "Struggle",
      "Cohesion",
      "Collaboration",
      "Communication",
      "Teamwork",
      "Feedback",
      "Improvement",
      "Stagnant",
      "Inhibit",
      "Inefficiency",
      "Delays",
      "Productivity",
      "Learning",
      "Development",
      "Enthusiasm",
    ],
  },
  {
    id: 6,
    month: "Sep 22",
    summary:
      "The team thrives in a vibrant and enjoyable culture, embracing a strong sense of camaraderie and creating a positive work environment. They value open communication, fostering connections, and building strong relationships. The team actively supports one another, cultivating a sense of unity and shared purpose. They prioritize work-life balance, encouraging well-being and personal growth. In this uplifting atmosphere, creativity flourishes, leading to inspired ideas and solutions. The team takes pleasure in their work, finding joy and fulfillment in their collective achievements. With their infectious enthusiasm, they radiate positivity and inspire others to embrace the culture they've cultivated. Overall, this team demonstrates a remarkable ability to enjoy the culture they've created, fostering a sense of fulfillment and satisfaction in their daily work experiences.",
    keywords: [
      "Thriving",
      "Vibrant",
      "Enjoyable",
      "Camaraderie",
      "Positive",
      "Open communication",
      "Connections",
      "Strong relationships",
      "Supportive",
      "Unity",
      "Purpose",
      "Work-life balance",
      "Well-being",
      "Creativity",
      "Fulfillment",
    ],
  },
  {
    id: 7,
    month: "Oct 22",
    summary:
      "The team exhibits a moderate level of engagement in their work culture, but there are opportunities for improvement. While they maintain some communication, there is room for enhancing collaboration and building stronger connections. They demonstrate a certain level of support for one another, but further efforts are needed to foster a more cohesive and unified environment. The team shows potential for personal growth, but there is a need for greater emphasis on individual development. Although they find some enjoyment in their work, there is room for cultivating a more positive and enthusiastic atmosphere. Overall, the team has the potential to enhance their work culture by investing in stronger communication, deeper collaboration, and a more uplifting environment, which would contribute to a more fulfilling and satisfying work experience.",
    keywords: [
      "Engagement",
      "Improvement",
      "Communication",
      "Collaboration",
      "Connection",
      "Support",
      "Cohesion",
      "Unity",
      "Growth",
      "Development",
      "Enjoyment",
      "Positivity",
      "Enthusiasm",
      "Potential",
      "Fulfillment",
    ],
  },
  {
    id: 8,
    month: "Nov 22",
    summary:
      "The team demonstrates a remarkable level of autonomy, with individuals taking ownership of their work and showing a high degree of self-reliance. They excel in effective communication, providing each other with necessary information and support when needed. The team's strong sense of independence allows for efficient decision-making and swift problem-solving. They exhibit a proclivity for taking initiative, actively seeking opportunities to contribute and make meaningful contributions to their projects. The team's autonomy fosters a sense of empowerment, allowing individuals to showcase their unique skills and talents. Overall, the team's ability to work autonomously not only promotes individual growth but also contributes to a dynamic and productive work environment where each member feels empowered to drive success.",
    keywords: [
      "Autonomy",
      "Ownership",
      "Self-reliance",
      "Communication",
      "Support",
      "Independence",
      "Decision-making",
      "Problem-solving",
      "Initiative",
      "Contribution",
      "Empowerment",
      "Skills",
      "Talents",
      "Growth",
      "Success",
    ],
  },
  {
    id: 9,
    month: "Dec 22",
    summary:
      "The team is led by a capable and inspiring leadership that sets a strong example for others. Their visionary guidance provides clarity of purpose and direction, empowering team members to reach their full potential. The leaders foster a culture of trust, openness, and collaboration, encouraging active participation and valuing diverse perspectives. They effectively communicate expectations and provide support, ensuring everyone is equipped with the resources needed to succeed. With their keen understanding of individual strengths, the leaders skillfully delegate tasks and allocate responsibilities, maximizing productivity and fostering a sense of ownership. The team benefits from the leaders' mentorship and guidance, creating a nurturing environment that promotes both personal and professional growth. Overall, the team thrives under the exceptional leadership, working cohesively towards shared goals and achieving remarkable outcomes.",
    keywords: [
      "Capable",
      "Inspiring",
      "Visionary",
      "Clarity",
      "Empowerment",
      "Trust",
      "Openness",
      "Collaboration",
      "Participation",
      "Diversity",
      "Communication",
      "Support",
      "Resources",
      "Delegation",
      "Mentorship",
    ],
  },
  {
    id: 10,
    month: "Jan 23",
    summary:
      "The team consistently delivers outstanding performance, surpassing expectations and setting a high standard for excellence. Their unwavering dedication and strong work ethic drive them towards success. They exhibit exceptional collaboration, effectively pooling their skills and knowledge to achieve collective goals. The team's synergy and seamless coordination enable them to tackle complex projects with ease. Their consistent focus on results and attention to detail ensure impeccable outcomes. The team's proactive approach and ability to adapt to changing circumstances showcase their agility and resilience. With a continuous commitment to improvement, they actively seek opportunities to enhance their performance and optimize their processes. Overall, the team's remarkable performance is a testament to their exceptional skills, teamwork, and relentless pursuit of excellence, making them a force to be reckoned with in their domain.",
    keywords: [
      "Outstanding",
      "Surpassing",
      "Excellence",
      "Dedication",
      "Work ethic",
      "Collaboration",
      "Synergy",
      "Coordination",
      "Results-focused",
      "Attention to detail",
      "Proactive",
      "Adaptability",
      "Resilience",
      "Continuous improvement",
      "Remarkable",
    ],
  },
  {
    id: 11,
    month: "Feb 23",
    summary:
      "The team struggles to consistently meet performance expectations, often falling short of desired outcomes. They face challenges in effective collaboration and fail to leverage their collective strengths. Coordination and communication issues hinder their ability to work cohesively towards shared goals. The team's attention to detail and commitment to results are lacking, resulting in subpar deliverables. Their reactive approach leaves them ill-prepared to handle unexpected obstacles, causing delays and setbacks. Despite some efforts towards improvement, the team's performance remains inconsistent and fails to meet desired standards. Overall, there is a clear need for stronger coordination, enhanced communication, and a more proactive mindset to address the team's performance shortcomings and achieve desired results.",
    keywords: [
      "Struggle",
      "Performance",
      "Expectations",
      "Collaboration",
      "Strengths",
      "Coordination",
      "Communication",
      "Cohesiveness",
      "Attention to detail",
      "Commitment",
      "Subpar",
      "Reactive",
      "Setbacks",
      "Inconsistent",
      "Improvement",
    ],
  },
  {
    id: 12,
    month: "Mar 23",
    summary:
      "The team embodies a spirit of adaptability and resilience, readily embracing change and tackling challenges head-on. Their open-mindedness and flexible approach allow them to navigate complex situations with ease. Effective communication and strong collaboration form the foundation of their work dynamic, fostering a harmonious and supportive environment. With a keen eye for detail and a commitment to quality, they consistently strive for excellence in their deliverables. The team's passion for continuous learning and growth is evident, as they actively seek opportunities to expand their skills and knowledge. Their shared enthusiasm and positive energy create a motivating atmosphere that fuels creativity and innovation. With their proactive mindset and efficient workflow, they consistently meet deadlines and exceed expectations. Overall, this team's adaptability, collaboration, and dedication to continuous improvement position them as a formidable force in their field.",
    keywords: [
      "Adaptability",
      "Resilience",
      "Open-mindedness",
      "Flexibility",
      "Communication",
      "Collaboration",
      "Harmony",
      "Supportive",
      "Detail-oriented",
      "Quality-focused",
      "Continuous learning",
      "Growth",
      "Enthusiasm",
      "Positive energy",
      "Proactive",
    ],
  },
  {
    id: 13,
    month: "Apr 23",
    summary:
      "The team's performance falls below expectations, struggling to meet the desired standards. They face significant challenges in collaboration, often experiencing breakdowns in communication and a lack of cohesive teamwork. The team's attention to detail is lacking, leading to errors and subpar work quality. Their reactive approach leaves them ill-prepared to handle unexpected obstacles, resulting in delays and missed opportunities. Despite some attempts at improvement, the team's performance remains consistently below average. Overall, there is a clear need for a major overhaul in their communication, teamwork, and attention to detail to bridge the performance gaps and achieve the desired level of success.",
    keywords: [
      "Under performance",
      "Struggle",
      "Collaboration",
      "Breakdowns",
      "Communication",
      "Teamwork",
      "Attention to detail",
      "Errors",
      "Subpar",
      "Reactive",
      "Delays",
      "Missed opportunities",
      "Improvement",
      "Overhaul",
      "Performance gaps",
    ],
  },
  {
    id: 14,
    month: "May 23",
    summary:
      "The team demonstrates a satisfactory level of performance, consistently meeting expectations and striving for improvement. They display a moderate level of collaboration, working together to overcome challenges and achieve their goals. While there may be occasional communication gaps, the team shows potential for stronger coordination and fostering a more cohesive environment. They exhibit a reasonable attention to detail, ensuring the quality of their work is generally acceptable. Although their approach can be reactive at times, the team is adaptable and willing to learn from past experiences. With ongoing efforts towards improvement, they have the potential to elevate their performance to a higher level. Overall, the team's dedication and willingness to grow contribute to a positive outlook, suggesting they are on a trajectory towards greater success.",
    keywords: [
      "Satisfactory",
      "Consistent",
      "Improvement",
      "Collaboration",
      "Challenges",
      "Goals",
      "Communication",
      "Coordination",
      "Cohesive",
      "Attention to detail",
      "Reactive",
      "Adaptable",
      "Learning",
      "Growth",
      "Potential",
    ],
  },
  {
    id: 15,
    month: "Jun 23",
    summary:
      "The team consistently delivers exceptional performance, exceeding expectations and setting a standard of excellence. They showcase a remarkable level of collaboration, seamlessly working together towards common goals. Effective communication and mutual support foster a cohesive and harmonious environment. The team's meticulous attention to detail ensures top-notch quality in their work, leaving no room for errors. Their proactive approach allows them to anticipate and address challenges before they become obstacles. The team's adaptability and resilience enable them to navigate complex situations with ease, turning setbacks into opportunities for growth. With their continuous drive for improvement, they consistently raise the bar and strive for even greater achievements. Overall, the team's exceptional performance, combined with their dedication and positive mindset, positions them as a true powerhouse in their field.",
    keywords: [
      "Exceptional",
      "Exceeding",
      "Collaboration",
      "Seamless",
      "Communication",
      "Support",
      "Cohesive",
      "Harmonious",
      "Meticulous",
      "Quality",
      "Proactive",
      "Adaptability",
      "Resilience",
      "Growth",
      "Achievement",
    ],
  },
  {
    id: 16,
    month: "Jul 23",
    summary:
      "The team thrives under exceptional leadership, guided by visionary individuals who inspire and empower their members. Their leaders demonstrate a clear sense of direction and purpose, setting high standards and encouraging the team to reach their full potential. Through effective communication and active listening, they foster a culture of trust and collaboration. The leaders value the unique strengths and contributions of each team member, skillfully leveraging their skills for optimal performance. They provide guidance and support, enabling individuals to grow both personally and professionally. With their inspiring leadership, the team feels motivated and driven to achieve extraordinary results. The leaders' unwavering dedication to the team's success creates a positive and uplifting work environment. Overall, the team's exceptional performance is a testament to the transformative impact of their leaders, who inspire greatness and guide the team towards continuous success.",
    keywords: [
      "Thriving",
      "Exceptional",
      "Visionary",
      "Inspire",
      "Empower",
      "Direction",
      "Purpose",
      "High standards",
      "Trust",
      "Collaboration",
      "Value",
      "Guidance",
      "Support",
      "Motivated",
      "Success",
    ],
  },
  {
    id: 17,
    month: "Last 3 Months",
    summary:
      "The team demonstrates a satisfactory level of performance, striving for improvement and displaying moderate collaboration. There is potential for stronger coordination and a more cohesive environment. They exhibit reasonable attention to detail and are adaptable in learning from past experiences. The team consistently exceeds expectations, showcasing exceptional collaboration and effective communication. Their meticulous attention to detail and proactive approach contribute to top-notch quality and the ability to anticipate challenges. Their adaptability and resilience enable them to navigate complex situations. Under exceptional leadership, the team is motivated, guided, and empowered to reach their full potential. The leaders foster a culture of trust and collaboration, valuing each team member's unique strengths. The team's exceptional performance is a testament to their transformative leaders, inspiring continuous success. Overall, the team's dedication, positive mindset, and exceptional leadership position them as a powerhouse in their field.",
    keywords: [
      "Satisfactory",
      "Improvement",
      "Moderate collaboration",
      "Coordination",
      "Cohesive",
      "Attention to detail",
      "Adaptable",
      "Exceeding expectations",
      "Exceptional collaboration",
      "Effective communication",
      "Anticipation",
      "Adaptability",
      "Resilience",
      "Leadership",
      "Empowerment",
    ],
  },
  {
    id: 18,
    month: "Last 6 Months",
    summary:
      "The team demonstrates a satisfactory level of performance, with potential for improvement. They exhibit a moderate level of collaboration, working together to overcome challenges. Communication gaps and coordination issues hinder their progress. Attention to detail and commitment to results require strengthening, leading to subpar deliverables. Their reactive approach creates delays and setbacks. However, their adaptability and resilience enable them to navigate complex situations. The team's proactive mindset, efficiency, and dedication to continuous learning foster a positive and motivating environment. They consistently strive for excellence and exceed expectations. Exceptional leadership sets high standards, fosters trust, and empowers team members. Overall, the team's remarkable performance, adaptability, collaboration, and leadership contribute to their position as a formidable force in their field. With stronger coordination, enhanced communication, and a proactive mindset, they can bridge performance gaps and achieve desired success.",
    keywords: [
      "Satisfactory",
      "Improvement",
      "Moderate",
      "Coordination",
      "Cohesion",
      "Detail",
      "Adaptable",
      "Expectations",
      "Collaboration",
      "Communication",
      "Proactive",
      "Quality",
      "Anticipate",
      "Resilience",
      "Leadership",
    ],
  },
  {
    id: 19,
    month: "Last 12 Months",
    summary:
      "The team exhibits a moderate level of engagement in their work culture, with opportunities for improvement. They demonstrate collaboration potential, yet stronger coordination and a cohesive environment are needed. There is reasonable attention to detail and adaptability to learn from past experiences. Exceptional performance defines the team, as they exceed expectations and display remarkable collaboration. Effective communication and mutual support foster a harmonious environment. Meticulous attention to detail ensures high-quality work, while a proactive approach anticipates and addresses challenges. The team's adaptability and resilience allow them to navigate complex situations. Under exceptional leadership, team members feel motivated and empowered, resulting in exceptional performance. Overall, the team shows potential for growth, with dedication and a positive outlook. Exceptional leadership drives success and creates a positive work environment.",
    keywords: [
      "Outstanding performance",
      "Collaboration",
      "Adaptability",
      "Resilience",
      "Continuous improvement",
      "Agility",
      "Excellence",
      "Proactive",
      "Innovation",
      "Trust",
      "Supportive environment",
      "Learning and growth",
      "Enthusiasm",
      "Positive energy",
      "Exceptional leadership",
    ],
  },
];

export const mobileTeamSummaryResult = [
  {
    id: 1,
    month: "Apr 22",
    summary:
      "It seems that people are feeling a sense of collaboration and teamwork. They appreciate the fact that the work was not done solely by themselves and that there was good communication through Slack.  The constant peer review suggests a culture of feedback and improvement. The approach of dividing and conquering sections of the work indicates efficient task allocation. The mention of learning and development highlights a focus on personal and professional growth. The elevator music during retro suggests a relaxed and enjoyable working environment. The quick delivery of initial dot points implies efficiency and responsiveness. Overall, the team seems open-minded, receptive to feedback, and working together on different sections, creating a positive and collaborative atmosphere.",
    keywords: [
      "Collaboration",
      "Teamwork",
      "Appreciation",
      "Communication",
      "Slack",
      "Peer review",
      "Feedback",
      "Improvement",
      "Task allocation",
      "Learning",
      "Development",
      "Personal",
      "Professional",
      "Environment",
      "Efficiency",
    ],
  },
  {
    id: 2,
    month: "May 22",
    summary:
      "The team demonstrates satisfactory performance, meeting basic expectations but lacking the ability to consistently excel. They exhibit a moderate level of collaboration, but there are occasional breakdowns in communication that hinder their progress. The team's attention to detail is acceptable, but there is room for improvement in terms of consistently delivering high-quality work. Their reactive approach sometimes leaves them struggling to proactively address challenges and seize opportunities. Despite making some efforts towards improvement, the team's performance remains average and fails to stand out from their peers. Overall, there is a need for greater focus, proactive problem-solving, and a stronger drive for excellence in order to elevate the team's performance to a higher level of success.",
    keywords: [
      "Satisfactory",
      "Moderate",
      "Breakdowns",
      "Acceptable",
      "Improvement",
      "Average",
      "Proactive",
      "Challenges",
      "Opportunities",
      "Efforts",
      "Focus",
      "Problem-solving",
      "Drive",
      "Excellence",
      "Success",
    ],
  },
  {
    id: 3,
    month: "Jun 22",
    summary:
      "The team appears to exhibit a moderate level of collaboration and teamwork. They acknowledge the importance of working together and value communication. While they engage in some peer review, there is room for improvement in terms of feedback and fostering a culture of continuous growth. Task allocation seems somewhat efficient with a division of work. They show a slight inclination towards learning and development. The presence of elevator music during retrospectives suggests a relatively relaxed working environment. The team demonstrates a moderate level of efficiency and responsiveness in delivering initial dot points. Overall, they display a certain level of openness and receptiveness to feedback while working on different sections, contributing to a moderately positive and collaborative atmosphere.",
    keywords: [
      "Collaboration",
      "Teamwork",
      "Communication",
      "Peer review",
      "Feedback",
      "Continuous growth",
      "Task allocation",
      "Efficiency",
      "Learning",
      "Development",
      "Relaxed",
      "Environment",
      "Responsiveness",
      "Openness",
      "Receptiveness",
    ],
  },
  {
    id: 4,
    month: "Jul 22",
    summary:
      "The team exemplifies a strong sense of synergy and mutual support, working together seamlessly to achieve their goals. They prioritize effective communication and actively foster an atmosphere of trust and respect. Through their cohesive efforts, they overcome challenges and demonstrate exceptional problem-solving skills. The team's innovative thinking and creative approaches generate fresh perspectives and propel them towards success. They embrace change and adaptability, consistently seeking new opportunities for growth and improvement. The team's dedication to excellence is evident in their meticulous attention to detail and commitment to delivering high-quality outcomes. With their unwavering focus on customer satisfaction, they consistently exceed expectations and maintain strong client relationships. Overall, this team embodies a spirit of innovation, collaboration, and unwavering commitment, making them a force to be reckoned with in their field.",
    keywords: [
      "Synergy",
      "Support",
      "Communication",
      "Trust",
      "Respect",
      "Cohesion",
      "Problem-solving",
      "Innovation",
      "Creativity",
      "Adaptability",
      "Growth",
      "Excellence",
      "Attention to detail",
      "Customer satisfaction",
      "Commitment",
    ],
  },
  {
    id: 5,
    month: "Aug 22",
    summary:
      "The team struggles to foster a cohesive and collaborative environment, often facing communication challenges and a lack of teamwork. Feedback and improvement are often overlooked, resulting in a stagnant culture that inhibits growth. Task allocation is inefficient, leading to delays and subpar productivity. Limited emphasis on learning and development hinders personal and professional growth. The working environment lacks enthusiasm and enjoyment, lacking the necessary elements to foster a positive atmosphere. Timeliness and responsiveness are areas that require improvement, as the team struggles to deliver prompt and efficient results. Overall, the team exhibits a lack of openness and receptiveness to feedback, hindering their ability to work together effectively and create a truly collaborative atmosphere.",
    keywords: [
      "Struggle",
      "Cohesion",
      "Collaboration",
      "Communication",
      "Teamwork",
      "Feedback",
      "Improvement",
      "Stagnant",
      "Inhibit",
      "Inefficiency",
      "Delays",
      "Productivity",
      "Learning",
      "Development",
      "Enthusiasm",
    ],
  },
  {
    id: 6,
    month: "Sep 22",
    summary:
      "The team thrives in a vibrant and enjoyable culture, embracing a strong sense of camaraderie and creating a positive work environment. They value open communication, fostering connections, and building strong relationships. The team actively supports one another, cultivating a sense of unity and shared purpose. They prioritize work-life balance, encouraging well-being and personal growth. In this uplifting atmosphere, creativity flourishes, leading to inspired ideas and solutions. The team takes pleasure in their work, finding joy and fulfillment in their collective achievements. With their infectious enthusiasm, they radiate positivity and inspire others to embrace the culture they've cultivated. Overall, this team demonstrates a remarkable ability to enjoy the culture they've created, fostering a sense of fulfillment and satisfaction in their daily work experiences.",
    keywords: [
      "Thriving",
      "Vibrant",
      "Enjoyable",
      "Camaraderie",
      "Positive",
      "Open communication",
      "Connections",
      "Strong relationships",
      "Supportive",
      "Unity",
      "Purpose",
      "Work-life balance",
      "Well-being",
      "Creativity",
      "Fulfillment",
    ],
  },
  {
    id: 7,
    month: "Oct 22",
    summary:
      "The team exhibits a moderate level of engagement in their work culture, but there are opportunities for improvement. While they maintain some communication, there is room for enhancing collaboration and building stronger connections. They demonstrate a certain level of support for one another, but further efforts are needed to foster a more cohesive and unified environment. The team shows potential for personal growth, but there is a need for greater emphasis on individual development. Although they find some enjoyment in their work, there is room for cultivating a more positive and enthusiastic atmosphere. Overall, the team has the potential to enhance their work culture by investing in stronger communication, deeper collaboration, and a more uplifting environment, which would contribute to a more fulfilling and satisfying work experience.",
    keywords: [
      "Engagement",
      "Improvement",
      "Communication",
      "Collaboration",
      "Connection",
      "Support",
      "Cohesion",
      "Unity",
      "Growth",
      "Development",
      "Enjoyment",
      "Positivity",
      "Enthusiasm",
      "Potential",
      "Fulfillment",
    ],
  },
  {
    id: 8,
    month: "Nov 22",
    summary:
      "The team demonstrates a remarkable level of autonomy, with individuals taking ownership of their work and showing a high degree of self-reliance. They excel in effective communication, providing each other with necessary information and support when needed. The team's strong sense of independence allows for efficient decision-making and swift problem-solving. They exhibit a proclivity for taking initiative, actively seeking opportunities to contribute and make meaningful contributions to their projects. The team's autonomy fosters a sense of empowerment, allowing individuals to showcase their unique skills and talents. Overall, the team's ability to work autonomously not only promotes individual growth but also contributes to a dynamic and productive work environment where each member feels empowered to drive success.",
    keywords: [
      "Autonomy",
      "Ownership",
      "Self-reliance",
      "Communication",
      "Support",
      "Independence",
      "Decision-making",
      "Problem-solving",
      "Initiative",
      "Contribution",
      "Empowerment",
      "Skills",
      "Talents",
      "Growth",
      "Success",
    ],
  },
  {
    id: 9,
    month: "Dec 22",
    summary:
      "The team is led by a capable and inspiring leadership that sets a strong example for others. Their visionary guidance provides clarity of purpose and direction, empowering team members to reach their full potential. The leaders foster a culture of trust, openness, and collaboration, encouraging active participation and valuing diverse perspectives. They effectively communicate expectations and provide support, ensuring everyone is equipped with the resources needed to succeed. With their keen understanding of individual strengths, the leaders skillfully delegate tasks and allocate responsibilities, maximizing productivity and fostering a sense of ownership. The team benefits from the leaders' mentorship and guidance, creating a nurturing environment that promotes both personal and professional growth. Overall, the team thrives under the exceptional leadership, working cohesively towards shared goals and achieving remarkable outcomes.",
    keywords: [
      "Capable",
      "Inspiring",
      "Visionary",
      "Clarity",
      "Empowerment",
      "Trust",
      "Openness",
      "Collaboration",
      "Participation",
      "Diversity",
      "Communication",
      "Support",
      "Resources",
      "Delegation",
      "Mentorship",
    ],
  },
  {
    id: 10,
    month: "Jan 23",
    summary:
      "The team consistently delivers outstanding performance, surpassing expectations and setting a high standard for excellence. Their unwavering dedication and strong work ethic drive them towards success. They exhibit exceptional collaboration, effectively pooling their skills and knowledge to achieve collective goals. The team's synergy and seamless coordination enable them to tackle complex projects with ease. Their consistent focus on results and attention to detail ensure impeccable outcomes. The team's proactive approach and ability to adapt to changing circumstances showcase their agility and resilience. With a continuous commitment to improvement, they actively seek opportunities to enhance their performance and optimize their processes. Overall, the team's remarkable performance is a testament to their exceptional skills, teamwork, and relentless pursuit of excellence, making them a force to be reckoned with in their domain.",
    keywords: [
      "Outstanding",
      "Surpassing",
      "Excellence",
      "Dedication",
      "Work ethic",
      "Collaboration",
      "Synergy",
      "Coordination",
      "Results-focused",
      "Attention to detail",
      "Proactive",
      "Adaptability",
      "Resilience",
      "Continuous improvement",
      "Remarkable",
    ],
  },
  {
    id: 11,
    month: "Feb 23",
    summary:
      "The team struggles to consistently meet performance expectations, often falling short of desired outcomes. They face challenges in effective collaboration and fail to leverage their collective strengths. Coordination and communication issues hinder their ability to work cohesively towards shared goals. The team's attention to detail and commitment to results are lacking, resulting in subpar deliverables. Their reactive approach leaves them ill-prepared to handle unexpected obstacles, causing delays and setbacks. Despite some efforts towards improvement, the team's performance remains inconsistent and fails to meet desired standards. Overall, there is a clear need for stronger coordination, enhanced communication, and a more proactive mindset to address the team's performance shortcomings and achieve desired results.",
    keywords: [
      "Struggle",
      "Performance",
      "Expectations",
      "Collaboration",
      "Strengths",
      "Coordination",
      "Communication",
      "Cohesiveness",
      "Attention to detail",
      "Commitment",
      "Subpar",
      "Reactive",
      "Setbacks",
      "Inconsistent",
      "Improvement",
    ],
  },
  {
    id: 12,
    month: "Mar 23",
    summary:
      "The team embodies a spirit of adaptability and resilience, readily embracing change and tackling challenges head-on. Their open-mindedness and flexible approach allow them to navigate complex situations with ease. Effective communication and strong collaboration form the foundation of their work dynamic, fostering a harmonious and supportive environment. With a keen eye for detail and a commitment to quality, they consistently strive for excellence in their deliverables. The team's passion for continuous learning and growth is evident, as they actively seek opportunities to expand their skills and knowledge. Their shared enthusiasm and positive energy create a motivating atmosphere that fuels creativity and innovation. With their proactive mindset and efficient workflow, they consistently meet deadlines and exceed expectations. Overall, this team's adaptability, collaboration, and dedication to continuous improvement position them as a formidable force in their field.",
    keywords: [
      "Adaptability",
      "Resilience",
      "Open-mindedness",
      "Flexibility",
      "Communication",
      "Collaboration",
      "Harmony",
      "Supportive",
      "Detail-oriented",
      "Quality-focused",
      "Continuous learning",
      "Growth",
      "Enthusiasm",
      "Positive energy",
      "Proactive",
    ],
  },
  {
    id: 13,
    month: "Apr 23",
    summary:
      "The team's performance falls below expectations, struggling to meet the desired standards. They face significant challenges in collaboration, often experiencing breakdowns in communication and a lack of cohesive teamwork. The team's attention to detail is lacking, leading to errors and subpar work quality. Their reactive approach leaves them ill-prepared to handle unexpected obstacles, resulting in delays and missed opportunities. Despite some attempts at improvement, the team's performance remains consistently below average. Overall, there is a clear need for a major overhaul in their communication, teamwork, and attention to detail to bridge the performance gaps and achieve the desired level of success.",
    keywords: [
      "Under performance",
      "Struggle",
      "Collaboration",
      "Breakdowns",
      "Communication",
      "Teamwork",
      "Attention to detail",
      "Errors",
      "Subpar",
      "Reactive",
      "Delays",
      "Missed opportunities",
      "Improvement",
      "Overhaul",
      "Performance gaps",
    ],
  },
  {
    id: 14,
    month: "May 23",
    summary:
      "The team demonstrates a satisfactory level of performance, consistently meeting expectations and striving for improvement. They display a moderate level of collaboration, working together to overcome challenges and achieve their goals. While there may be occasional communication gaps, the team shows potential for stronger coordination and fostering a more cohesive environment. They exhibit a reasonable attention to detail, ensuring the quality of their work is generally acceptable. Although their approach can be reactive at times, the team is adaptable and willing to learn from past experiences. With ongoing efforts towards improvement, they have the potential to elevate their performance to a higher level. Overall, the team's dedication and willingness to grow contribute to a positive outlook, suggesting they are on a trajectory towards greater success.",
    keywords: [
      "Satisfactory",
      "Consistent",
      "Improvement",
      "Collaboration",
      "Challenges",
      "Goals",
      "Communication",
      "Coordination",
      "Cohesive",
      "Attention to detail",
      "Reactive",
      "Adaptable",
      "Learning",
      "Growth",
      "Potential",
    ],
  },
  {
    id: 15,
    month: "Jun 23",
    summary:
      "The team consistently delivers exceptional performance, exceeding expectations and setting a standard of excellence. They showcase a remarkable level of collaboration, seamlessly working together towards common goals. Effective communication and mutual support foster a cohesive and harmonious environment. The team's meticulous attention to detail ensures top-notch quality in their work, leaving no room for errors. Their proactive approach allows them to anticipate and address challenges before they become obstacles. The team's adaptability and resilience enable them to navigate complex situations with ease, turning setbacks into opportunities for growth. With their continuous drive for improvement, they consistently raise the bar and strive for even greater achievements. Overall, the team's exceptional performance, combined with their dedication and positive mindset, positions them as a true powerhouse in their field.",
    keywords: [
      "Exceptional",
      "Exceeding",
      "Collaboration",
      "Seamless",
      "Communication",
      "Support",
      "Cohesive",
      "Harmonious",
      "Meticulous",
      "Quality",
      "Proactive",
      "Adaptability",
      "Resilience",
      "Growth",
      "Achievement",
    ],
  },
  {
    id: 16,
    month: "Jul 23",
    summary:
      "The team thrives under exceptional leadership, guided by visionary individuals who inspire and empower their members. Their leaders demonstrate a clear sense of direction and purpose, setting high standards and encouraging the team to reach their full potential. Through effective communication and active listening, they foster a culture of trust and collaboration. The leaders value the unique strengths and contributions of each team member, skillfully leveraging their skills for optimal performance. They provide guidance and support, enabling individuals to grow both personally and professionally. With their inspiring leadership, the team feels motivated and driven to achieve extraordinary results. The leaders' unwavering dedication to the team's success creates a positive and uplifting work environment. Overall, the team's exceptional performance is a testament to the transformative impact of their leaders, who inspire greatness and guide the team towards continuous success.",
    keywords: [
      "Thriving",
      "Exceptional",
      "Visionary",
      "Inspire",
      "Empower",
      "Direction",
      "Purpose",
      "High standards",
      "Trust",
      "Collaboration",
      "Value",
      "Guidance",
      "Support",
      "Motivated",
      "Success",
    ],
  },
  {
    id: 17,
    month: "Last 3 Months",
    summary:
      "The team demonstrates a satisfactory level of performance, striving for improvement and displaying moderate collaboration. There is potential for stronger coordination and a more cohesive environment. They exhibit reasonable attention to detail and are adaptable in learning from past experiences. The team consistently exceeds expectations, showcasing exceptional collaboration and effective communication. Their meticulous attention to detail and proactive approach contribute to top-notch quality and the ability to anticipate challenges. Their adaptability and resilience enable them to navigate complex situations. Under exceptional leadership, the team is motivated, guided, and empowered to reach their full potential. The leaders foster a culture of trust and collaboration, valuing each team member's unique strengths. The team's exceptional performance is a testament to their transformative leaders, inspiring continuous success. Overall, the team's dedication, positive mindset, and exceptional leadership position them as a powerhouse in their field.",
    keywords: [
      "Satisfactory",
      "Improvement",
      "Moderate collaboration",
      "Coordination",
      "Cohesive",
      "Attention to detail",
      "Adaptable",
      "Exceeding expectations",
      "Exceptional collaboration",
      "Effective communication",
      "Anticipation",
      "Adaptability",
      "Resilience",
      "Leadership",
      "Empowerment",
    ],
  },
  {
    id: 18,
    month: "Last 6 Months",
    summary:
      "The team demonstrates a satisfactory level of performance, with potential for improvement. They exhibit a moderate level of collaboration, working together to overcome challenges. Communication gaps and coordination issues hinder their progress. Attention to detail and commitment to results require strengthening, leading to subpar deliverables. Their reactive approach creates delays and setbacks. However, their adaptability and resilience enable them to navigate complex situations. The team's proactive mindset, efficiency, and dedication to continuous learning foster a positive and motivating environment. They consistently strive for excellence and exceed expectations. Exceptional leadership sets high standards, fosters trust, and empowers team members. Overall, the team's remarkable performance, adaptability, collaboration, and leadership contribute to their position as a formidable force in their field. With stronger coordination, enhanced communication, and a proactive mindset, they can bridge performance gaps and achieve desired success.",
    keywords: [
      "Satisfactory",
      "Improvement",
      "Moderate",
      "Coordination",
      "Cohesion",
      "Detail",
      "Adaptable",
      "Expectations",
      "Collaboration",
      "Communication",
      "Proactive",
      "Quality",
      "Anticipate",
      "Resilience",
      "Leadership",
    ],
  },
  {
    id: 19,
    month: "Last 12 Months",
    summary:
      "The team exhibits a moderate level of engagement in their work culture, with opportunities for improvement. They demonstrate collaboration potential, yet stronger coordination and a cohesive environment are needed. There is reasonable attention to detail and adaptability to learn from past experiences. Exceptional performance defines the team, as they exceed expectations and display remarkable collaboration. Effective communication and mutual support foster a harmonious environment. Meticulous attention to detail ensures high-quality work, while a proactive approach anticipates and addresses challenges. The team's adaptability and resilience allow them to navigate complex situations. Under exceptional leadership, team members feel motivated and empowered, resulting in exceptional performance. Overall, the team shows potential for growth, with dedication and a positive outlook. Exceptional leadership drives success and creates a positive work environment.",
    keywords: [
      "Outstanding performance",
      "Collaboration",
      "Adaptability",
      "Resilience",
      "Continuous improvement",
      "Agility",
      "Excellence",
      "Proactive",
      "Innovation",
      "Trust",
      "Supportive environment",
      "Learning and growth",
      "Enthusiasm",
      "Positive energy",
      "Exceptional leadership",
    ],
  },
];

export const superannuationTeamSummaryResult = [
  {
    id: 1,
    month: "Apr 22",
    summary:
      "It seems that people are feeling a sense of collaboration and teamwork. They appreciate the fact that the work was not done solely by themselves and that there was good communication through Slack.  The constant peer review suggests a culture of feedback and improvement. The approach of dividing and conquering sections of the work indicates efficient task allocation. The mention of learning and development highlights a focus on personal and professional growth. The elevator music during retro suggests a relaxed and enjoyable working environment. The quick delivery of initial dot points implies efficiency and responsiveness. Overall, the team seems open-minded, receptive to feedback, and working together on different sections, creating a positive and collaborative atmosphere.",
    keywords: [
      "Collaboration",
      "Teamwork",
      "Appreciation",
      "Communication",
      "Slack",
      "Peer review",
      "Feedback",
      "Improvement",
      "Task allocation",
      "Learning",
      "Development",
      "Personal",
      "Professional",
      "Environment",
      "Efficiency",
    ],
  },
  {
    id: 2,
    month: "May 22",
    summary:
      "The team demonstrates satisfactory performance, meeting basic expectations but lacking the ability to consistently excel. They exhibit a moderate level of collaboration, but there are occasional breakdowns in communication that hinder their progress. The team's attention to detail is acceptable, but there is room for improvement in terms of consistently delivering high-quality work. Their reactive approach sometimes leaves them struggling to proactively address challenges and seize opportunities. Despite making some efforts towards improvement, the team's performance remains average and fails to stand out from their peers. Overall, there is a need for greater focus, proactive problem-solving, and a stronger drive for excellence in order to elevate the team's performance to a higher level of success.",
    keywords: [
      "Satisfactory",
      "Moderate",
      "Breakdowns",
      "Acceptable",
      "Improvement",
      "Average",
      "Proactive",
      "Challenges",
      "Opportunities",
      "Efforts",
      "Focus",
      "Problem-solving",
      "Drive",
      "Excellence",
      "Success",
    ],
  },
  {
    id: 3,
    month: "Jun 22",
    summary:
      "The team appears to exhibit a moderate level of collaboration and teamwork. They acknowledge the importance of working together and value communication. While they engage in some peer review, there is room for improvement in terms of feedback and fostering a culture of continuous growth. Task allocation seems somewhat efficient with a division of work. They show a slight inclination towards learning and development. The presence of elevator music during retrospectives suggests a relatively relaxed working environment. The team demonstrates a moderate level of efficiency and responsiveness in delivering initial dot points. Overall, they display a certain level of openness and receptiveness to feedback while working on different sections, contributing to a moderately positive and collaborative atmosphere.",
    keywords: [
      "Collaboration",
      "Teamwork",
      "Communication",
      "Peer review",
      "Feedback",
      "Continuous growth",
      "Task allocation",
      "Efficiency",
      "Learning",
      "Development",
      "Relaxed",
      "Environment",
      "Responsiveness",
      "Openness",
      "Receptiveness",
    ],
  },
  {
    id: 4,
    month: "Jul 22",
    summary:
      "The team exemplifies a strong sense of synergy and mutual support, working together seamlessly to achieve their goals. They prioritize effective communication and actively foster an atmosphere of trust and respect. Through their cohesive efforts, they overcome challenges and demonstrate exceptional problem-solving skills. The team's innovative thinking and creative approaches generate fresh perspectives and propel them towards success. They embrace change and adaptability, consistently seeking new opportunities for growth and improvement. The team's dedication to excellence is evident in their meticulous attention to detail and commitment to delivering high-quality outcomes. With their unwavering focus on customer satisfaction, they consistently exceed expectations and maintain strong client relationships. Overall, this team embodies a spirit of innovation, collaboration, and unwavering commitment, making them a force to be reckoned with in their field.",
    keywords: [
      "Synergy",
      "Support",
      "Communication",
      "Trust",
      "Respect",
      "Cohesion",
      "Problem-solving",
      "Innovation",
      "Creativity",
      "Adaptability",
      "Growth",
      "Excellence",
      "Attention to detail",
      "Customer satisfaction",
      "Commitment",
    ],
  },
  {
    id: 5,
    month: "Aug 22",
    summary:
      "The team struggles to foster a cohesive and collaborative environment, often facing communication challenges and a lack of teamwork. Feedback and improvement are often overlooked, resulting in a stagnant culture that inhibits growth. Task allocation is inefficient, leading to delays and subpar productivity. Limited emphasis on learning and development hinders personal and professional growth. The working environment lacks enthusiasm and enjoyment, lacking the necessary elements to foster a positive atmosphere. Timeliness and responsiveness are areas that require improvement, as the team struggles to deliver prompt and efficient results. Overall, the team exhibits a lack of openness and receptiveness to feedback, hindering their ability to work together effectively and create a truly collaborative atmosphere.",
    keywords: [
      "Struggle",
      "Cohesion",
      "Collaboration",
      "Communication",
      "Teamwork",
      "Feedback",
      "Improvement",
      "Stagnant",
      "Inhibit",
      "Inefficiency",
      "Delays",
      "Productivity",
      "Learning",
      "Development",
      "Enthusiasm",
    ],
  },
  {
    id: 6,
    month: "Sep 22",
    summary:
      "The team thrives in a vibrant and enjoyable culture, embracing a strong sense of camaraderie and creating a positive work environment. They value open communication, fostering connections, and building strong relationships. The team actively supports one another, cultivating a sense of unity and shared purpose. They prioritize work-life balance, encouraging well-being and personal growth. In this uplifting atmosphere, creativity flourishes, leading to inspired ideas and solutions. The team takes pleasure in their work, finding joy and fulfillment in their collective achievements. With their infectious enthusiasm, they radiate positivity and inspire others to embrace the culture they've cultivated. Overall, this team demonstrates a remarkable ability to enjoy the culture they've created, fostering a sense of fulfillment and satisfaction in their daily work experiences.",
    keywords: [
      "Thriving",
      "Vibrant",
      "Enjoyable",
      "Camaraderie",
      "Positive",
      "Open communication",
      "Connections",
      "Strong relationships",
      "Supportive",
      "Unity",
      "Purpose",
      "Work-life balance",
      "Well-being",
      "Creativity",
      "Fulfillment",
    ],
  },
  {
    id: 7,
    month: "Oct 22",
    summary:
      "The team exhibits a moderate level of engagement in their work culture, but there are opportunities for improvement. While they maintain some communication, there is room for enhancing collaboration and building stronger connections. They demonstrate a certain level of support for one another, but further efforts are needed to foster a more cohesive and unified environment. The team shows potential for personal growth, but there is a need for greater emphasis on individual development. Although they find some enjoyment in their work, there is room for cultivating a more positive and enthusiastic atmosphere. Overall, the team has the potential to enhance their work culture by investing in stronger communication, deeper collaboration, and a more uplifting environment, which would contribute to a more fulfilling and satisfying work experience.",
    keywords: [
      "Engagement",
      "Improvement",
      "Communication",
      "Collaboration",
      "Connection",
      "Support",
      "Cohesion",
      "Unity",
      "Growth",
      "Development",
      "Enjoyment",
      "Positivity",
      "Enthusiasm",
      "Potential",
      "Fulfillment",
    ],
  },
  {
    id: 8,
    month: "Nov 22",
    summary:
      "The team demonstrates a remarkable level of autonomy, with individuals taking ownership of their work and showing a high degree of self-reliance. They excel in effective communication, providing each other with necessary information and support when needed. The team's strong sense of independence allows for efficient decision-making and swift problem-solving. They exhibit a proclivity for taking initiative, actively seeking opportunities to contribute and make meaningful contributions to their projects. The team's autonomy fosters a sense of empowerment, allowing individuals to showcase their unique skills and talents. Overall, the team's ability to work autonomously not only promotes individual growth but also contributes to a dynamic and productive work environment where each member feels empowered to drive success.",
    keywords: [
      "Autonomy",
      "Ownership",
      "Self-reliance",
      "Communication",
      "Support",
      "Independence",
      "Decision-making",
      "Problem-solving",
      "Initiative",
      "Contribution",
      "Empowerment",
      "Skills",
      "Talents",
      "Growth",
      "Success",
    ],
  },
  {
    id: 9,
    month: "Dec 22",
    summary:
      "The team is led by a capable and inspiring leadership that sets a strong example for others. Their visionary guidance provides clarity of purpose and direction, empowering team members to reach their full potential. The leaders foster a culture of trust, openness, and collaboration, encouraging active participation and valuing diverse perspectives. They effectively communicate expectations and provide support, ensuring everyone is equipped with the resources needed to succeed. With their keen understanding of individual strengths, the leaders skillfully delegate tasks and allocate responsibilities, maximizing productivity and fostering a sense of ownership. The team benefits from the leaders' mentorship and guidance, creating a nurturing environment that promotes both personal and professional growth. Overall, the team thrives under the exceptional leadership, working cohesively towards shared goals and achieving remarkable outcomes.",
    keywords: [
      "Capable",
      "Inspiring",
      "Visionary",
      "Clarity",
      "Empowerment",
      "Trust",
      "Openness",
      "Collaboration",
      "Participation",
      "Diversity",
      "Communication",
      "Support",
      "Resources",
      "Delegation",
      "Mentorship",
    ],
  },
  {
    id: 10,
    month: "Jan 23",
    summary:
      "The team consistently delivers outstanding performance, surpassing expectations and setting a high standard for excellence. Their unwavering dedication and strong work ethic drive them towards success. They exhibit exceptional collaboration, effectively pooling their skills and knowledge to achieve collective goals. The team's synergy and seamless coordination enable them to tackle complex projects with ease. Their consistent focus on results and attention to detail ensure impeccable outcomes. The team's proactive approach and ability to adapt to changing circumstances showcase their agility and resilience. With a continuous commitment to improvement, they actively seek opportunities to enhance their performance and optimize their processes. Overall, the team's remarkable performance is a testament to their exceptional skills, teamwork, and relentless pursuit of excellence, making them a force to be reckoned with in their domain.",
    keywords: [
      "Outstanding",
      "Surpassing",
      "Excellence",
      "Dedication",
      "Work ethic",
      "Collaboration",
      "Synergy",
      "Coordination",
      "Results-focused",
      "Attention to detail",
      "Proactive",
      "Adaptability",
      "Resilience",
      "Continuous improvement",
      "Remarkable",
    ],
  },
  {
    id: 11,
    month: "Feb 23",
    summary:
      "The team struggles to consistently meet performance expectations, often falling short of desired outcomes. They face challenges in effective collaboration and fail to leverage their collective strengths. Coordination and communication issues hinder their ability to work cohesively towards shared goals. The team's attention to detail and commitment to results are lacking, resulting in subpar deliverables. Their reactive approach leaves them ill-prepared to handle unexpected obstacles, causing delays and setbacks. Despite some efforts towards improvement, the team's performance remains inconsistent and fails to meet desired standards. Overall, there is a clear need for stronger coordination, enhanced communication, and a more proactive mindset to address the team's performance shortcomings and achieve desired results.",
    keywords: [
      "Struggle",
      "Performance",
      "Expectations",
      "Collaboration",
      "Strengths",
      "Coordination",
      "Communication",
      "Cohesiveness",
      "Attention to detail",
      "Commitment",
      "Subpar",
      "Reactive",
      "Setbacks",
      "Inconsistent",
      "Improvement",
    ],
  },
  {
    id: 12,
    month: "Mar 23",
    summary:
      "The team embodies a spirit of adaptability and resilience, readily embracing change and tackling challenges head-on. Their open-mindedness and flexible approach allow them to navigate complex situations with ease. Effective communication and strong collaboration form the foundation of their work dynamic, fostering a harmonious and supportive environment. With a keen eye for detail and a commitment to quality, they consistently strive for excellence in their deliverables. The team's passion for continuous learning and growth is evident, as they actively seek opportunities to expand their skills and knowledge. Their shared enthusiasm and positive energy create a motivating atmosphere that fuels creativity and innovation. With their proactive mindset and efficient workflow, they consistently meet deadlines and exceed expectations. Overall, this team's adaptability, collaboration, and dedication to continuous improvement position them as a formidable force in their field.",
    keywords: [
      "Adaptability",
      "Resilience",
      "Open-mindedness",
      "Flexibility",
      "Communication",
      "Collaboration",
      "Harmony",
      "Supportive",
      "Detail-oriented",
      "Quality-focused",
      "Continuous learning",
      "Growth",
      "Enthusiasm",
      "Positive energy",
      "Proactive",
    ],
  },
  {
    id: 13,
    month: "Apr 23",
    summary:
      "The team's performance falls below expectations, struggling to meet the desired standards. They face significant challenges in collaboration, often experiencing breakdowns in communication and a lack of cohesive teamwork. The team's attention to detail is lacking, leading to errors and subpar work quality. Their reactive approach leaves them ill-prepared to handle unexpected obstacles, resulting in delays and missed opportunities. Despite some attempts at improvement, the team's performance remains consistently below average. Overall, there is a clear need for a major overhaul in their communication, teamwork, and attention to detail to bridge the performance gaps and achieve the desired level of success.",
    keywords: [
      "Under performance",
      "Struggle",
      "Collaboration",
      "Breakdowns",
      "Communication",
      "Teamwork",
      "Attention to detail",
      "Errors",
      "Subpar",
      "Reactive",
      "Delays",
      "Missed opportunities",
      "Improvement",
      "Overhaul",
      "Performance gaps",
    ],
  },
  {
    id: 14,
    month: "May 23",
    summary:
      "The team demonstrates a satisfactory level of performance, consistently meeting expectations and striving for improvement. They display a moderate level of collaboration, working together to overcome challenges and achieve their goals. While there may be occasional communication gaps, the team shows potential for stronger coordination and fostering a more cohesive environment. They exhibit a reasonable attention to detail, ensuring the quality of their work is generally acceptable. Although their approach can be reactive at times, the team is adaptable and willing to learn from past experiences. With ongoing efforts towards improvement, they have the potential to elevate their performance to a higher level. Overall, the team's dedication and willingness to grow contribute to a positive outlook, suggesting they are on a trajectory towards greater success.",
    keywords: [
      "Satisfactory",
      "Consistent",
      "Improvement",
      "Collaboration",
      "Challenges",
      "Goals",
      "Communication",
      "Coordination",
      "Cohesive",
      "Attention to detail",
      "Reactive",
      "Adaptable",
      "Learning",
      "Growth",
      "Potential",
    ],
  },
  {
    id: 15,
    month: "Jun 23",
    summary:
      "The team consistently delivers exceptional performance, exceeding expectations and setting a standard of excellence. They showcase a remarkable level of collaboration, seamlessly working together towards common goals. Effective communication and mutual support foster a cohesive and harmonious environment. The team's meticulous attention to detail ensures top-notch quality in their work, leaving no room for errors. Their proactive approach allows them to anticipate and address challenges before they become obstacles. The team's adaptability and resilience enable them to navigate complex situations with ease, turning setbacks into opportunities for growth. With their continuous drive for improvement, they consistently raise the bar and strive for even greater achievements. Overall, the team's exceptional performance, combined with their dedication and positive mindset, positions them as a true powerhouse in their field.",
    keywords: [
      "Exceptional",
      "Exceeding",
      "Collaboration",
      "Seamless",
      "Communication",
      "Support",
      "Cohesive",
      "Harmonious",
      "Meticulous",
      "Quality",
      "Proactive",
      "Adaptability",
      "Resilience",
      "Growth",
      "Achievement",
    ],
  },
  {
    id: 16,
    month: "Jul 23",
    summary:
      "The team thrives under exceptional leadership, guided by visionary individuals who inspire and empower their members. Their leaders demonstrate a clear sense of direction and purpose, setting high standards and encouraging the team to reach their full potential. Through effective communication and active listening, they foster a culture of trust and collaboration. The leaders value the unique strengths and contributions of each team member, skillfully leveraging their skills for optimal performance. They provide guidance and support, enabling individuals to grow both personally and professionally. With their inspiring leadership, the team feels motivated and driven to achieve extraordinary results. The leaders' unwavering dedication to the team's success creates a positive and uplifting work environment. Overall, the team's exceptional performance is a testament to the transformative impact of their leaders, who inspire greatness and guide the team towards continuous success.",
    keywords: [
      "Thriving",
      "Exceptional",
      "Visionary",
      "Inspire",
      "Empower",
      "Direction",
      "Purpose",
      "High standards",
      "Trust",
      "Collaboration",
      "Value",
      "Guidance",
      "Support",
      "Motivated",
      "Success",
    ],
  },
  {
    id: 17,
    month: "Last 3 Months",
    summary:
      "The team demonstrates a satisfactory level of performance, striving for improvement and displaying moderate collaboration. There is potential for stronger coordination and a more cohesive environment. They exhibit reasonable attention to detail and are adaptable in learning from past experiences. The team consistently exceeds expectations, showcasing exceptional collaboration and effective communication. Their meticulous attention to detail and proactive approach contribute to top-notch quality and the ability to anticipate challenges. Their adaptability and resilience enable them to navigate complex situations. Under exceptional leadership, the team is motivated, guided, and empowered to reach their full potential. The leaders foster a culture of trust and collaboration, valuing each team member's unique strengths. The team's exceptional performance is a testament to their transformative leaders, inspiring continuous success. Overall, the team's dedication, positive mindset, and exceptional leadership position them as a powerhouse in their field.",
    keywords: [
      "Satisfactory",
      "Improvement",
      "Moderate collaboration",
      "Coordination",
      "Cohesive",
      "Attention to detail",
      "Adaptable",
      "Exceeding expectations",
      "Exceptional collaboration",
      "Effective communication",
      "Anticipation",
      "Adaptability",
      "Resilience",
      "Leadership",
      "Empowerment",
    ],
  },
  {
    id: 18,
    month: "Last 6 Months",
    summary:
      "The team demonstrates a satisfactory level of performance, with potential for improvement. They exhibit a moderate level of collaboration, working together to overcome challenges. Communication gaps and coordination issues hinder their progress. Attention to detail and commitment to results require strengthening, leading to subpar deliverables. Their reactive approach creates delays and setbacks. However, their adaptability and resilience enable them to navigate complex situations. The team's proactive mindset, efficiency, and dedication to continuous learning foster a positive and motivating environment. They consistently strive for excellence and exceed expectations. Exceptional leadership sets high standards, fosters trust, and empowers team members. Overall, the team's remarkable performance, adaptability, collaboration, and leadership contribute to their position as a formidable force in their field. With stronger coordination, enhanced communication, and a proactive mindset, they can bridge performance gaps and achieve desired success.",
    keywords: [
      "Satisfactory",
      "Improvement",
      "Moderate",
      "Coordination",
      "Cohesion",
      "Detail",
      "Adaptable",
      "Expectations",
      "Collaboration",
      "Communication",
      "Proactive",
      "Quality",
      "Anticipate",
      "Resilience",
      "Leadership",
    ],
  },
  {
    id: 19,
    month: "Last 12 Months",
    summary:
      "The team exhibits a moderate level of engagement in their work culture, with opportunities for improvement. They demonstrate collaboration potential, yet stronger coordination and a cohesive environment are needed. There is reasonable attention to detail and adaptability to learn from past experiences. Exceptional performance defines the team, as they exceed expectations and display remarkable collaboration. Effective communication and mutual support foster a harmonious environment. Meticulous attention to detail ensures high-quality work, while a proactive approach anticipates and addresses challenges. The team's adaptability and resilience allow them to navigate complex situations. Under exceptional leadership, team members feel motivated and empowered, resulting in exceptional performance. Overall, the team shows potential for growth, with dedication and a positive outlook. Exceptional leadership drives success and creates a positive work environment.",
    keywords: [
      "Outstanding performance",
      "Collaboration",
      "Adaptability",
      "Resilience",
      "Continuous improvement",
      "Agility",
      "Excellence",
      "Proactive",
      "Innovation",
      "Trust",
      "Supportive environment",
      "Learning and growth",
      "Enthusiasm",
      "Positive energy",
      "Exceptional leadership",
    ],
  },
];

export const insuranceTeamSummaryResult = [
  {
    id: 1,
    month: "Apr 22",
    summary:
      "It seems that people are feeling a sense of collaboration and teamwork. They appreciate the fact that the work was not done solely by themselves and that there was good communication through Slack.  The constant peer review suggests a culture of feedback and improvement. The approach of dividing and conquering sections of the work indicates efficient task allocation. The mention of learning and development highlights a focus on personal and professional growth. The elevator music during retro suggests a relaxed and enjoyable working environment. The quick delivery of initial dot points implies efficiency and responsiveness. Overall, the team seems open-minded, receptive to feedback, and working together on different sections, creating a positive and collaborative atmosphere.",
    keywords: [
      "Collaboration",
      "Teamwork",
      "Appreciation",
      "Communication",
      "Slack",
      "Peer review",
      "Feedback",
      "Improvement",
      "Task allocation",
      "Learning",
      "Development",
      "Personal",
      "Professional",
      "Environment",
      "Efficiency",
    ],
  },
  {
    id: 2,
    month: "May 22",
    summary:
      "The team demonstrates satisfactory performance, meeting basic expectations but lacking the ability to consistently excel. They exhibit a moderate level of collaboration, but there are occasional breakdowns in communication that hinder their progress. The team's attention to detail is acceptable, but there is room for improvement in terms of consistently delivering high-quality work. Their reactive approach sometimes leaves them struggling to proactively address challenges and seize opportunities. Despite making some efforts towards improvement, the team's performance remains average and fails to stand out from their peers. Overall, there is a need for greater focus, proactive problem-solving, and a stronger drive for excellence in order to elevate the team's performance to a higher level of success.",
    keywords: [
      "Satisfactory",
      "Moderate",
      "Breakdowns",
      "Acceptable",
      "Improvement",
      "Average",
      "Proactive",
      "Challenges",
      "Opportunities",
      "Efforts",
      "Focus",
      "Problem-solving",
      "Drive",
      "Excellence",
      "Success",
    ],
  },
  {
    id: 3,
    month: "Jun 22",
    summary:
      "The team appears to exhibit a moderate level of collaboration and teamwork. They acknowledge the importance of working together and value communication. While they engage in some peer review, there is room for improvement in terms of feedback and fostering a culture of continuous growth. Task allocation seems somewhat efficient with a division of work. They show a slight inclination towards learning and development. The presence of elevator music during retrospectives suggests a relatively relaxed working environment. The team demonstrates a moderate level of efficiency and responsiveness in delivering initial dot points. Overall, they display a certain level of openness and receptiveness to feedback while working on different sections, contributing to a moderately positive and collaborative atmosphere.",
    keywords: [
      "Collaboration",
      "Teamwork",
      "Communication",
      "Peer review",
      "Feedback",
      "Continuous growth",
      "Task allocation",
      "Efficiency",
      "Learning",
      "Development",
      "Relaxed",
      "Environment",
      "Responsiveness",
      "Openness",
      "Receptiveness",
    ],
  },
  {
    id: 4,
    month: "Jul 22",
    summary:
      "The team exemplifies a strong sense of synergy and mutual support, working together seamlessly to achieve their goals. They prioritize effective communication and actively foster an atmosphere of trust and respect. Through their cohesive efforts, they overcome challenges and demonstrate exceptional problem-solving skills. The team's innovative thinking and creative approaches generate fresh perspectives and propel them towards success. They embrace change and adaptability, consistently seeking new opportunities for growth and improvement. The team's dedication to excellence is evident in their meticulous attention to detail and commitment to delivering high-quality outcomes. With their unwavering focus on customer satisfaction, they consistently exceed expectations and maintain strong client relationships. Overall, this team embodies a spirit of innovation, collaboration, and unwavering commitment, making them a force to be reckoned with in their field.",
    keywords: [
      "Synergy",
      "Support",
      "Communication",
      "Trust",
      "Respect",
      "Cohesion",
      "Problem-solving",
      "Innovation",
      "Creativity",
      "Adaptability",
      "Growth",
      "Excellence",
      "Attention to detail",
      "Customer satisfaction",
      "Commitment",
    ],
  },
  {
    id: 5,
    month: "Aug 22",
    summary:
      "The team struggles to foster a cohesive and collaborative environment, often facing communication challenges and a lack of teamwork. Feedback and improvement are often overlooked, resulting in a stagnant culture that inhibits growth. Task allocation is inefficient, leading to delays and subpar productivity. Limited emphasis on learning and development hinders personal and professional growth. The working environment lacks enthusiasm and enjoyment, lacking the necessary elements to foster a positive atmosphere. Timeliness and responsiveness are areas that require improvement, as the team struggles to deliver prompt and efficient results. Overall, the team exhibits a lack of openness and receptiveness to feedback, hindering their ability to work together effectively and create a truly collaborative atmosphere.",
    keywords: [
      "Struggle",
      "Cohesion",
      "Collaboration",
      "Communication",
      "Teamwork",
      "Feedback",
      "Improvement",
      "Stagnant",
      "Inhibit",
      "Inefficiency",
      "Delays",
      "Productivity",
      "Learning",
      "Development",
      "Enthusiasm",
    ],
  },
  {
    id: 6,
    month: "Sep 22",
    summary:
      "The team thrives in a vibrant and enjoyable culture, embracing a strong sense of camaraderie and creating a positive work environment. They value open communication, fostering connections, and building strong relationships. The team actively supports one another, cultivating a sense of unity and shared purpose. They prioritize work-life balance, encouraging well-being and personal growth. In this uplifting atmosphere, creativity flourishes, leading to inspired ideas and solutions. The team takes pleasure in their work, finding joy and fulfillment in their collective achievements. With their infectious enthusiasm, they radiate positivity and inspire others to embrace the culture they've cultivated. Overall, this team demonstrates a remarkable ability to enjoy the culture they've created, fostering a sense of fulfillment and satisfaction in their daily work experiences.",
    keywords: [
      "Thriving",
      "Vibrant",
      "Enjoyable",
      "Camaraderie",
      "Positive",
      "Open communication",
      "Connections",
      "Strong relationships",
      "Supportive",
      "Unity",
      "Purpose",
      "Work-life balance",
      "Well-being",
      "Creativity",
      "Fulfillment",
    ],
  },
  {
    id: 7,
    month: "Oct 22",
    summary:
      "The team exhibits a moderate level of engagement in their work culture, but there are opportunities for improvement. While they maintain some communication, there is room for enhancing collaboration and building stronger connections. They demonstrate a certain level of support for one another, but further efforts are needed to foster a more cohesive and unified environment. The team shows potential for personal growth, but there is a need for greater emphasis on individual development. Although they find some enjoyment in their work, there is room for cultivating a more positive and enthusiastic atmosphere. Overall, the team has the potential to enhance their work culture by investing in stronger communication, deeper collaboration, and a more uplifting environment, which would contribute to a more fulfilling and satisfying work experience.",
    keywords: [
      "Engagement",
      "Improvement",
      "Communication",
      "Collaboration",
      "Connection",
      "Support",
      "Cohesion",
      "Unity",
      "Growth",
      "Development",
      "Enjoyment",
      "Positivity",
      "Enthusiasm",
      "Potential",
      "Fulfillment",
    ],
  },
  {
    id: 8,
    month: "Nov 22",
    summary:
      "The team demonstrates a remarkable level of autonomy, with individuals taking ownership of their work and showing a high degree of self-reliance. They excel in effective communication, providing each other with necessary information and support when needed. The team's strong sense of independence allows for efficient decision-making and swift problem-solving. They exhibit a proclivity for taking initiative, actively seeking opportunities to contribute and make meaningful contributions to their projects. The team's autonomy fosters a sense of empowerment, allowing individuals to showcase their unique skills and talents. Overall, the team's ability to work autonomously not only promotes individual growth but also contributes to a dynamic and productive work environment where each member feels empowered to drive success.",
    keywords: [
      "Autonomy",
      "Ownership",
      "Self-reliance",
      "Communication",
      "Support",
      "Independence",
      "Decision-making",
      "Problem-solving",
      "Initiative",
      "Contribution",
      "Empowerment",
      "Skills",
      "Talents",
      "Growth",
      "Success",
    ],
  },
  {
    id: 9,
    month: "Dec 22",
    summary:
      "The team is led by a capable and inspiring leadership that sets a strong example for others. Their visionary guidance provides clarity of purpose and direction, empowering team members to reach their full potential. The leaders foster a culture of trust, openness, and collaboration, encouraging active participation and valuing diverse perspectives. They effectively communicate expectations and provide support, ensuring everyone is equipped with the resources needed to succeed. With their keen understanding of individual strengths, the leaders skillfully delegate tasks and allocate responsibilities, maximizing productivity and fostering a sense of ownership. The team benefits from the leaders' mentorship and guidance, creating a nurturing environment that promotes both personal and professional growth. Overall, the team thrives under the exceptional leadership, working cohesively towards shared goals and achieving remarkable outcomes.",
    keywords: [
      "Capable",
      "Inspiring",
      "Visionary",
      "Clarity",
      "Empowerment",
      "Trust",
      "Openness",
      "Collaboration",
      "Participation",
      "Diversity",
      "Communication",
      "Support",
      "Resources",
      "Delegation",
      "Mentorship",
    ],
  },
  {
    id: 10,
    month: "Jan 23",
    summary:
      "The team consistently delivers outstanding performance, surpassing expectations and setting a high standard for excellence. Their unwavering dedication and strong work ethic drive them towards success. They exhibit exceptional collaboration, effectively pooling their skills and knowledge to achieve collective goals. The team's synergy and seamless coordination enable them to tackle complex projects with ease. Their consistent focus on results and attention to detail ensure impeccable outcomes. The team's proactive approach and ability to adapt to changing circumstances showcase their agility and resilience. With a continuous commitment to improvement, they actively seek opportunities to enhance their performance and optimize their processes. Overall, the team's remarkable performance is a testament to their exceptional skills, teamwork, and relentless pursuit of excellence, making them a force to be reckoned with in their domain.",
    keywords: [
      "Outstanding",
      "Surpassing",
      "Excellence",
      "Dedication",
      "Work ethic",
      "Collaboration",
      "Synergy",
      "Coordination",
      "Results-focused",
      "Attention to detail",
      "Proactive",
      "Adaptability",
      "Resilience",
      "Continuous improvement",
      "Remarkable",
    ],
  },
  {
    id: 11,
    month: "Feb 23",
    summary:
      "The team struggles to consistently meet performance expectations, often falling short of desired outcomes. They face challenges in effective collaboration and fail to leverage their collective strengths. Coordination and communication issues hinder their ability to work cohesively towards shared goals. The team's attention to detail and commitment to results are lacking, resulting in subpar deliverables. Their reactive approach leaves them ill-prepared to handle unexpected obstacles, causing delays and setbacks. Despite some efforts towards improvement, the team's performance remains inconsistent and fails to meet desired standards. Overall, there is a clear need for stronger coordination, enhanced communication, and a more proactive mindset to address the team's performance shortcomings and achieve desired results.",
    keywords: [
      "Struggle",
      "Performance",
      "Expectations",
      "Collaboration",
      "Strengths",
      "Coordination",
      "Communication",
      "Cohesiveness",
      "Attention to detail",
      "Commitment",
      "Subpar",
      "Reactive",
      "Setbacks",
      "Inconsistent",
      "Improvement",
    ],
  },
  {
    id: 12,
    month: "Mar 23",
    summary:
      "The team embodies a spirit of adaptability and resilience, readily embracing change and tackling challenges head-on. Their open-mindedness and flexible approach allow them to navigate complex situations with ease. Effective communication and strong collaboration form the foundation of their work dynamic, fostering a harmonious and supportive environment. With a keen eye for detail and a commitment to quality, they consistently strive for excellence in their deliverables. The team's passion for continuous learning and growth is evident, as they actively seek opportunities to expand their skills and knowledge. Their shared enthusiasm and positive energy create a motivating atmosphere that fuels creativity and innovation. With their proactive mindset and efficient workflow, they consistently meet deadlines and exceed expectations. Overall, this team's adaptability, collaboration, and dedication to continuous improvement position them as a formidable force in their field.",
    keywords: [
      "Adaptability",
      "Resilience",
      "Open-mindedness",
      "Flexibility",
      "Communication",
      "Collaboration",
      "Harmony",
      "Supportive",
      "Detail-oriented",
      "Quality-focused",
      "Continuous learning",
      "Growth",
      "Enthusiasm",
      "Positive energy",
      "Proactive",
    ],
  },
  {
    id: 13,
    month: "Apr 23",
    summary:
      "The team's performance falls below expectations, struggling to meet the desired standards. They face significant challenges in collaboration, often experiencing breakdowns in communication and a lack of cohesive teamwork. The team's attention to detail is lacking, leading to errors and subpar work quality. Their reactive approach leaves them ill-prepared to handle unexpected obstacles, resulting in delays and missed opportunities. Despite some attempts at improvement, the team's performance remains consistently below average. Overall, there is a clear need for a major overhaul in their communication, teamwork, and attention to detail to bridge the performance gaps and achieve the desired level of success.",
    keywords: [
      "Under performance",
      "Struggle",
      "Collaboration",
      "Breakdowns",
      "Communication",
      "Teamwork",
      "Attention to detail",
      "Errors",
      "Subpar",
      "Reactive",
      "Delays",
      "Missed opportunities",
      "Improvement",
      "Overhaul",
      "Performance gaps",
    ],
  },
  {
    id: 14,
    month: "May 23",
    summary:
      "The team demonstrates a satisfactory level of performance, consistently meeting expectations and striving for improvement. They display a moderate level of collaboration, working together to overcome challenges and achieve their goals. While there may be occasional communication gaps, the team shows potential for stronger coordination and fostering a more cohesive environment. They exhibit a reasonable attention to detail, ensuring the quality of their work is generally acceptable. Although their approach can be reactive at times, the team is adaptable and willing to learn from past experiences. With ongoing efforts towards improvement, they have the potential to elevate their performance to a higher level. Overall, the team's dedication and willingness to grow contribute to a positive outlook, suggesting they are on a trajectory towards greater success.",
    keywords: [
      "Satisfactory",
      "Consistent",
      "Improvement",
      "Collaboration",
      "Challenges",
      "Goals",
      "Communication",
      "Coordination",
      "Cohesive",
      "Attention to detail",
      "Reactive",
      "Adaptable",
      "Learning",
      "Growth",
      "Potential",
    ],
  },
  {
    id: 15,
    month: "Jun 23",
    summary:
      "The team consistently delivers exceptional performance, exceeding expectations and setting a standard of excellence. They showcase a remarkable level of collaboration, seamlessly working together towards common goals. Effective communication and mutual support foster a cohesive and harmonious environment. The team's meticulous attention to detail ensures top-notch quality in their work, leaving no room for errors. Their proactive approach allows them to anticipate and address challenges before they become obstacles. The team's adaptability and resilience enable them to navigate complex situations with ease, turning setbacks into opportunities for growth. With their continuous drive for improvement, they consistently raise the bar and strive for even greater achievements. Overall, the team's exceptional performance, combined with their dedication and positive mindset, positions them as a true powerhouse in their field.",
    keywords: [
      "Exceptional",
      "Exceeding",
      "Collaboration",
      "Seamless",
      "Communication",
      "Support",
      "Cohesive",
      "Harmonious",
      "Meticulous",
      "Quality",
      "Proactive",
      "Adaptability",
      "Resilience",
      "Growth",
      "Achievement",
    ],
  },
  {
    id: 16,
    month: "Jul 23",
    summary:
      "The team thrives under exceptional leadership, guided by visionary individuals who inspire and empower their members. Their leaders demonstrate a clear sense of direction and purpose, setting high standards and encouraging the team to reach their full potential. Through effective communication and active listening, they foster a culture of trust and collaboration. The leaders value the unique strengths and contributions of each team member, skillfully leveraging their skills for optimal performance. They provide guidance and support, enabling individuals to grow both personally and professionally. With their inspiring leadership, the team feels motivated and driven to achieve extraordinary results. The leaders' unwavering dedication to the team's success creates a positive and uplifting work environment. Overall, the team's exceptional performance is a testament to the transformative impact of their leaders, who inspire greatness and guide the team towards continuous success.",
    keywords: [
      "Thriving",
      "Exceptional",
      "Visionary",
      "Inspire",
      "Empower",
      "Direction",
      "Purpose",
      "High standards",
      "Trust",
      "Collaboration",
      "Value",
      "Guidance",
      "Support",
      "Motivated",
      "Success",
    ],
  },
  {
    id: 17,
    month: "Last 3 Months",
    summary:
      "The team demonstrates a satisfactory level of performance, striving for improvement and displaying moderate collaboration. There is potential for stronger coordination and a more cohesive environment. They exhibit reasonable attention to detail and are adaptable in learning from past experiences. The team consistently exceeds expectations, showcasing exceptional collaboration and effective communication. Their meticulous attention to detail and proactive approach contribute to top-notch quality and the ability to anticipate challenges. Their adaptability and resilience enable them to navigate complex situations. Under exceptional leadership, the team is motivated, guided, and empowered to reach their full potential. The leaders foster a culture of trust and collaboration, valuing each team member's unique strengths. The team's exceptional performance is a testament to their transformative leaders, inspiring continuous success. Overall, the team's dedication, positive mindset, and exceptional leadership position them as a powerhouse in their field.",
    keywords: [
      "Satisfactory",
      "Improvement",
      "Moderate collaboration",
      "Coordination",
      "Cohesive",
      "Attention to detail",
      "Adaptable",
      "Exceeding expectations",
      "Exceptional collaboration",
      "Effective communication",
      "Anticipation",
      "Adaptability",
      "Resilience",
      "Leadership",
      "Empowerment",
    ],
  },
  {
    id: 18,
    month: "Last 6 Months",
    summary:
      "The team demonstrates a satisfactory level of performance, with potential for improvement. They exhibit a moderate level of collaboration, working together to overcome challenges. Communication gaps and coordination issues hinder their progress. Attention to detail and commitment to results require strengthening, leading to subpar deliverables. Their reactive approach creates delays and setbacks. However, their adaptability and resilience enable them to navigate complex situations. The team's proactive mindset, efficiency, and dedication to continuous learning foster a positive and motivating environment. They consistently strive for excellence and exceed expectations. Exceptional leadership sets high standards, fosters trust, and empowers team members. Overall, the team's remarkable performance, adaptability, collaboration, and leadership contribute to their position as a formidable force in their field. With stronger coordination, enhanced communication, and a proactive mindset, they can bridge performance gaps and achieve desired success.",
    keywords: [
      "Satisfactory",
      "Improvement",
      "Moderate",
      "Coordination",
      "Cohesion",
      "Detail",
      "Adaptable",
      "Expectations",
      "Collaboration",
      "Communication",
      "Proactive",
      "Quality",
      "Anticipate",
      "Resilience",
      "Leadership",
    ],
  },
  {
    id: 19,
    month: "Last 12 Months",
    summary:
      "The team exhibits a moderate level of engagement in their work culture, with opportunities for improvement. They demonstrate collaboration potential, yet stronger coordination and a cohesive environment are needed. There is reasonable attention to detail and adaptability to learn from past experiences. Exceptional performance defines the team, as they exceed expectations and display remarkable collaboration. Effective communication and mutual support foster a harmonious environment. Meticulous attention to detail ensures high-quality work, while a proactive approach anticipates and addresses challenges. The team's adaptability and resilience allow them to navigate complex situations. Under exceptional leadership, team members feel motivated and empowered, resulting in exceptional performance. Overall, the team shows potential for growth, with dedication and a positive outlook. Exceptional leadership drives success and creates a positive work environment.",
    keywords: [
      "Outstanding performance",
      "Collaboration",
      "Adaptability",
      "Resilience",
      "Continuous improvement",
      "Agility",
      "Excellence",
      "Proactive",
      "Innovation",
      "Trust",
      "Supportive environment",
      "Learning and growth",
      "Enthusiasm",
      "Positive energy",
      "Exceptional leadership",
    ],
  },
];
