export const allTeamsSummaryResult = [
  {
    id: 1,
    month: "Last Month",
    summary:
      "The team thrives under exceptional leadership, guided by visionary individuals who inspire and empower their members. Their leaders demonstrate a clear sense of direction and purpose, setting high standards and encouraging the team to reach their full potential. Through effective communication and active listening, they foster a culture of trust and collaboration. The leaders value the unique strengths and contributions of each team member, skillfully leveraging their skills for optimal performance. They provide guidance and support, enabling individuals to grow both personally and professionally. With their inspiring leadership, the team feels motivated and driven to achieve extraordinary results. The leaders' unwavering dedication to the team's success creates a positive and uplifting work environment. Overall, the team's exceptional performance is a testament to the transformative impact of their leaders, who inspire greatness and guide the team towards continuous success.",
    keywords: [
      "Thriving",
      "Exceptional",
      "Visionary",
      "Inspire",
      "Empower",
      "Direction",
      "Purpose",
      "High standards",
      "Trust",
      "Collaboration",
      "Value",
      "Guidance",
      "Support",
      "Motivated",
      "Success",
    ],
  },
  {
    id: 2,
    month: "Last 3 Months",
    summary:
      "The team demonstrates a satisfactory level of performance, striving for improvement and displaying moderate collaboration. There is potential for stronger coordination and a more cohesive environment. They exhibit reasonable attention to detail and are adaptable in learning from past experiences. The team consistently exceeds expectations, showcasing exceptional collaboration and effective communication. Their meticulous attention to detail and proactive approach contribute to top-notch quality and the ability to anticipate challenges. Their adaptability and resilience enable them to navigate complex situations. Under exceptional leadership, the team is motivated, guided, and empowered to reach their full potential. The leaders foster a culture of trust and collaboration, valuing each team member's unique strengths. The team's exceptional performance is a testament to their transformative leaders, inspiring continuous success. Overall, the team's dedication, positive mindset, and exceptional leadership position them as a powerhouse in their field.",
    keywords: [
      "Satisfactory",
      "Improvement",
      "Moderate collaboration",
      "Coordination",
      "Cohesive",
      "Attention to detail",
      "Adaptable",
      "Exceeding expectations",
      "Exceptional collaboration",
      "Effective communication",
      "Anticipation",
      "Adaptability",
      "Resilience",
      "Leadership",
      "Empowerment",
    ],
  },
  {
    id: 3,
    month: "Last 6 Months",
    summary:
      "The team demonstrates a satisfactory level of performance, with potential for improvement. They exhibit a moderate level of collaboration, working together to overcome challenges. Communication gaps and coordination issues hinder their progress. Attention to detail and commitment to results require strengthening, leading to subpar deliverables. Their reactive approach creates delays and setbacks. However, their adaptability and resilience enable them to navigate complex situations. The team's proactive mindset, efficiency, and dedication to continuous learning foster a positive and motivating environment. They consistently strive for excellence and exceed expectations. Exceptional leadership sets high standards, fosters trust, and empowers team members. Overall, the team's remarkable performance, adaptability, collaboration, and leadership contribute to their position as a formidable force in their field. With stronger coordination, enhanced communication, and a proactive mindset, they can bridge performance gaps and achieve desired success.",
    keywords: [
      "Satisfactory",
      "Improvement",
      "Moderate",
      "Coordination",
      "Cohesion",
      "Detail",
      "Adaptable",
      "Expectations",
      "Collaboration",
      "Communication",
      "Proactive",
      "Quality",
      "Anticipate",
      "Resilience",
      "Leadership",
    ],
  },
  {
    id: 4,
    month: "Last 12 Months",
    summary:
      "The team exhibits a moderate level of engagement in their work culture, with opportunities for improvement. They demonstrate collaboration potential, yet stronger coordination and a cohesive environment are needed. There is reasonable attention to detail and adaptability to learn from past experiences. Exceptional performance defines the team, as they exceed expectations and display remarkable collaboration. Effective communication and mutual support foster a harmonious environment. Meticulous attention to detail ensures high-quality work, while a proactive approach anticipates and addresses challenges. The team's adaptability and resilience allow them to navigate complex situations. Under exceptional leadership, team members feel motivated and empowered, resulting in exceptional performance. Overall, the team shows potential for growth, with dedication and a positive outlook. Exceptional leadership drives success and creates a positive work environment.",
    keywords: [
      "Outstanding performance",
      "Collaboration",
      "Adaptability",
      "Resilience",
      "Continuous improvement",
      "Agility",
      "Excellence",
      "Proactive",
      "Innovation",
      "Trust",
      "Supportive environment",
      "Learning and growth",
      "Enthusiasm",
      "Positive energy",
      "Exceptional leadership",
    ],
  },
];

export const mobileTeamSummaryResult = [
  {
    id: 1,
    month: "Last Month",
    summary:
      "The team thrives under exceptional leadership, guided by visionary individuals who inspire and empower their members. Their leaders demonstrate a clear sense of direction and purpose, setting high standards and encouraging the team to reach their full potential. Through effective communication and active listening, they foster a culture of trust and collaboration. The leaders value the unique strengths and contributions of each team member, skillfully leveraging their skills for optimal performance. They provide guidance and support, enabling individuals to grow both personally and professionally. With their inspiring leadership, the team feels motivated and driven to achieve extraordinary results. The leaders' unwavering dedication to the team's success creates a positive and uplifting work environment. Overall, the team's exceptional performance is a testament to the transformative impact of their leaders, who inspire greatness and guide the team towards continuous success.",
    keywords: [
      "Thriving",
      "Exceptional",
      "Visionary",
      "Inspire",
      "Empower",
      "Direction",
      "Purpose",
      "High standards",
      "Trust",
      "Collaboration",
      "Value",
      "Guidance",
      "Support",
      "Motivated",
      "Success",
    ],
  },
  {
    id: 2,
    month: "Last 3 Months",
    summary:
      "The team demonstrates a satisfactory level of performance, striving for improvement and displaying moderate collaboration. There is potential for stronger coordination and a more cohesive environment. They exhibit reasonable attention to detail and are adaptable in learning from past experiences. The team consistently exceeds expectations, showcasing exceptional collaboration and effective communication. Their meticulous attention to detail and proactive approach contribute to top-notch quality and the ability to anticipate challenges. Their adaptability and resilience enable them to navigate complex situations. Under exceptional leadership, the team is motivated, guided, and empowered to reach their full potential. The leaders foster a culture of trust and collaboration, valuing each team member's unique strengths. The team's exceptional performance is a testament to their transformative leaders, inspiring continuous success. Overall, the team's dedication, positive mindset, and exceptional leadership position them as a powerhouse in their field.",
    keywords: [
      "Satisfactory",
      "Improvement",
      "Moderate collaboration",
      "Coordination",
      "Cohesive",
      "Attention to detail",
      "Adaptable",
      "Exceeding expectations",
      "Exceptional collaboration",
      "Effective communication",
      "Anticipation",
      "Adaptability",
      "Resilience",
      "Leadership",
      "Empowerment",
    ],
  },
  {
    id: 3,
    month: "Last 6 Months",
    summary:
      "The team demonstrates a satisfactory level of performance, with potential for improvement. They exhibit a moderate level of collaboration, working together to overcome challenges. Communication gaps and coordination issues hinder their progress. Attention to detail and commitment to results require strengthening, leading to subpar deliverables. Their reactive approach creates delays and setbacks. However, their adaptability and resilience enable them to navigate complex situations. The team's proactive mindset, efficiency, and dedication to continuous learning foster a positive and motivating environment. They consistently strive for excellence and exceed expectations. Exceptional leadership sets high standards, fosters trust, and empowers team members. Overall, the team's remarkable performance, adaptability, collaboration, and leadership contribute to their position as a formidable force in their field. With stronger coordination, enhanced communication, and a proactive mindset, they can bridge performance gaps and achieve desired success.",
    keywords: [
      "Satisfactory",
      "Improvement",
      "Moderate",
      "Coordination",
      "Cohesion",
      "Detail",
      "Adaptable",
      "Expectations",
      "Collaboration",
      "Communication",
      "Proactive",
      "Quality",
      "Anticipate",
      "Resilience",
      "Leadership",
    ],
  },
  {
    id: 4,
    month: "Last 12 Months",
    summary:
      "The team exhibits a moderate level of engagement in their work culture, with opportunities for improvement. They demonstrate collaboration potential, yet stronger coordination and a cohesive environment are needed. There is reasonable attention to detail and adaptability to learn from past experiences. Exceptional performance defines the team, as they exceed expectations and display remarkable collaboration. Effective communication and mutual support foster a harmonious environment. Meticulous attention to detail ensures high-quality work, while a proactive approach anticipates and addresses challenges. The team's adaptability and resilience allow them to navigate complex situations. Under exceptional leadership, team members feel motivated and empowered, resulting in exceptional performance. Overall, the team shows potential for growth, with dedication and a positive outlook. Exceptional leadership drives success and creates a positive work environment.",
    keywords: [
      "Outstanding performance",
      "Collaboration",
      "Adaptability",
      "Resilience",
      "Continuous improvement",
      "Agility",
      "Excellence",
      "Proactive",
      "Innovation",
      "Trust",
      "Supportive environment",
      "Learning and growth",
      "Enthusiasm",
      "Positive energy",
      "Exceptional leadership",
    ],
  },
];

export const superannuationTeamSummaryResult = [
  {
    id: 1,
    month: "Last Month",
    summary:
      "The team thrives under exceptional leadership, guided by visionary individuals who inspire and empower their members. Their leaders demonstrate a clear sense of direction and purpose, setting high standards and encouraging the team to reach their full potential. Through effective communication and active listening, they foster a culture of trust and collaboration. The leaders value the unique strengths and contributions of each team member, skillfully leveraging their skills for optimal performance. They provide guidance and support, enabling individuals to grow both personally and professionally. With their inspiring leadership, the team feels motivated and driven to achieve extraordinary results. The leaders' unwavering dedication to the team's success creates a positive and uplifting work environment. Overall, the team's exceptional performance is a testament to the transformative impact of their leaders, who inspire greatness and guide the team towards continuous success.",
    keywords: [
      "Thriving",
      "Exceptional",
      "Visionary",
      "Inspire",
      "Empower",
      "Direction",
      "Purpose",
      "High standards",
      "Trust",
      "Collaboration",
      "Value",
      "Guidance",
      "Support",
      "Motivated",
      "Success",
    ],
  },
  {
    id: 2,
    month: "Last 3 Months",
    summary:
      "The team demonstrates a satisfactory level of performance, striving for improvement and displaying moderate collaboration. There is potential for stronger coordination and a more cohesive environment. They exhibit reasonable attention to detail and are adaptable in learning from past experiences. The team consistently exceeds expectations, showcasing exceptional collaboration and effective communication. Their meticulous attention to detail and proactive approach contribute to top-notch quality and the ability to anticipate challenges. Their adaptability and resilience enable them to navigate complex situations. Under exceptional leadership, the team is motivated, guided, and empowered to reach their full potential. The leaders foster a culture of trust and collaboration, valuing each team member's unique strengths. The team's exceptional performance is a testament to their transformative leaders, inspiring continuous success. Overall, the team's dedication, positive mindset, and exceptional leadership position them as a powerhouse in their field.",
    keywords: [
      "Satisfactory",
      "Improvement",
      "Moderate collaboration",
      "Coordination",
      "Cohesive",
      "Attention to detail",
      "Adaptable",
      "Exceeding expectations",
      "Exceptional collaboration",
      "Effective communication",
      "Anticipation",
      "Adaptability",
      "Resilience",
      "Leadership",
      "Empowerment",
    ],
  },
  {
    id: 3,
    month: "Last 6 Months",
    summary:
      "The team demonstrates a satisfactory level of performance, with potential for improvement. They exhibit a moderate level of collaboration, working together to overcome challenges. Communication gaps and coordination issues hinder their progress. Attention to detail and commitment to results require strengthening, leading to subpar deliverables. Their reactive approach creates delays and setbacks. However, their adaptability and resilience enable them to navigate complex situations. The team's proactive mindset, efficiency, and dedication to continuous learning foster a positive and motivating environment. They consistently strive for excellence and exceed expectations. Exceptional leadership sets high standards, fosters trust, and empowers team members. Overall, the team's remarkable performance, adaptability, collaboration, and leadership contribute to their position as a formidable force in their field. With stronger coordination, enhanced communication, and a proactive mindset, they can bridge performance gaps and achieve desired success.",
    keywords: [
      "Satisfactory",
      "Improvement",
      "Moderate",
      "Coordination",
      "Cohesion",
      "Detail",
      "Adaptable",
      "Expectations",
      "Collaboration",
      "Communication",
      "Proactive",
      "Quality",
      "Anticipate",
      "Resilience",
      "Leadership",
    ],
  },
  {
    id: 4,
    month: "Last 12 Months",
    summary:
      "The team exhibits a moderate level of engagement in their work culture, with opportunities for improvement. They demonstrate collaboration potential, yet stronger coordination and a cohesive environment are needed. There is reasonable attention to detail and adaptability to learn from past experiences. Exceptional performance defines the team, as they exceed expectations and display remarkable collaboration. Effective communication and mutual support foster a harmonious environment. Meticulous attention to detail ensures high-quality work, while a proactive approach anticipates and addresses challenges. The team's adaptability and resilience allow them to navigate complex situations. Under exceptional leadership, team members feel motivated and empowered, resulting in exceptional performance. Overall, the team shows potential for growth, with dedication and a positive outlook. Exceptional leadership drives success and creates a positive work environment.",
    keywords: [
      "Outstanding performance",
      "Collaboration",
      "Adaptability",
      "Resilience",
      "Continuous improvement",
      "Agility",
      "Excellence",
      "Proactive",
      "Innovation",
      "Trust",
      "Supportive environment",
      "Learning and growth",
      "Enthusiasm",
      "Positive energy",
      "Exceptional leadership",
    ],
  },
];

export const insuranceTeamSummaryResult = [
  {
    id: 1,
    month: "Last Month",
    summary:
      "The team thrives under exceptional leadership, guided by visionary individuals who inspire and empower their members. Their leaders demonstrate a clear sense of direction and purpose, setting high standards and encouraging the team to reach their full potential. Through effective communication and active listening, they foster a culture of trust and collaboration. The leaders value the unique strengths and contributions of each team member, skillfully leveraging their skills for optimal performance. They provide guidance and support, enabling individuals to grow both personally and professionally. With their inspiring leadership, the team feels motivated and driven to achieve extraordinary results. The leaders' unwavering dedication to the team's success creates a positive and uplifting work environment. Overall, the team's exceptional performance is a testament to the transformative impact of their leaders, who inspire greatness and guide the team towards continuous success.",
    keywords: [
      "Thriving",
      "Exceptional",
      "Visionary",
      "Inspire",
      "Empower",
      "Direction",
      "Purpose",
      "High standards",
      "Trust",
      "Collaboration",
      "Value",
      "Guidance",
      "Support",
      "Motivated",
      "Success",
    ],
  },
  {
    id: 2,
    month: "Last 3 Months",
    summary:
      "The team demonstrates a satisfactory level of performance, striving for improvement and displaying moderate collaboration. There is potential for stronger coordination and a more cohesive environment. They exhibit reasonable attention to detail and are adaptable in learning from past experiences. The team consistently exceeds expectations, showcasing exceptional collaboration and effective communication. Their meticulous attention to detail and proactive approach contribute to top-notch quality and the ability to anticipate challenges. Their adaptability and resilience enable them to navigate complex situations. Under exceptional leadership, the team is motivated, guided, and empowered to reach their full potential. The leaders foster a culture of trust and collaboration, valuing each team member's unique strengths. The team's exceptional performance is a testament to their transformative leaders, inspiring continuous success. Overall, the team's dedication, positive mindset, and exceptional leadership position them as a powerhouse in their field.",
    keywords: [
      "Satisfactory",
      "Improvement",
      "Moderate collaboration",
      "Coordination",
      "Cohesive",
      "Attention to detail",
      "Adaptable",
      "Exceeding expectations",
      "Exceptional collaboration",
      "Effective communication",
      "Anticipation",
      "Adaptability",
      "Resilience",
      "Leadership",
      "Empowerment",
    ],
  },
  {
    id: 3,
    month: "Last 6 Months",
    summary:
      "The team demonstrates a satisfactory level of performance, with potential for improvement. They exhibit a moderate level of collaboration, working together to overcome challenges. Communication gaps and coordination issues hinder their progress. Attention to detail and commitment to results require strengthening, leading to subpar deliverables. Their reactive approach creates delays and setbacks. However, their adaptability and resilience enable them to navigate complex situations. The team's proactive mindset, efficiency, and dedication to continuous learning foster a positive and motivating environment. They consistently strive for excellence and exceed expectations. Exceptional leadership sets high standards, fosters trust, and empowers team members. Overall, the team's remarkable performance, adaptability, collaboration, and leadership contribute to their position as a formidable force in their field. With stronger coordination, enhanced communication, and a proactive mindset, they can bridge performance gaps and achieve desired success.",
    keywords: [
      "Satisfactory",
      "Improvement",
      "Moderate",
      "Coordination",
      "Cohesion",
      "Detail",
      "Adaptable",
      "Expectations",
      "Collaboration",
      "Communication",
      "Proactive",
      "Quality",
      "Anticipate",
      "Resilience",
      "Leadership",
    ],
  },
  {
    id: 4,
    month: "Last 12 Months",
    summary:
      "The team exhibits a moderate level of engagement in their work culture, with opportunities for improvement. They demonstrate collaboration potential, yet stronger coordination and a cohesive environment are needed. There is reasonable attention to detail and adaptability to learn from past experiences. Exceptional performance defines the team, as they exceed expectations and display remarkable collaboration. Effective communication and mutual support foster a harmonious environment. Meticulous attention to detail ensures high-quality work, while a proactive approach anticipates and addresses challenges. The team's adaptability and resilience allow them to navigate complex situations. Under exceptional leadership, team members feel motivated and empowered, resulting in exceptional performance. Overall, the team shows potential for growth, with dedication and a positive outlook. Exceptional leadership drives success and creates a positive work environment.",
    keywords: [
      "Outstanding performance",
      "Collaboration",
      "Adaptability",
      "Resilience",
      "Continuous improvement",
      "Agility",
      "Excellence",
      "Proactive",
      "Innovation",
      "Trust",
      "Supportive environment",
      "Learning and growth",
      "Enthusiasm",
      "Positive energy",
      "Exceptional leadership",
    ],
  },
];
