name: Trigger auto deployment for dev-api-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ dev ]
    paths:
    - '**'
    - '.github/workflows/dev-api-container-app-AutoDeployTrigger-2d003e4e-6c78-4fab-9dc7-479e8052cc6c.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

env:
  DOCKLE_TIMEOUT_SEC: 600s

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: bacibackend.azurecr.io
          username: ${{ secrets.DEVAPICONTAINERAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.DEVAPICONTAINERAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bacibackend.azurecr.io/backend-dev:${{ github.sha }}
          file: ./Dockerfile
          context: ./

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: bacibackend.azurecr.io/backend-dev:${{ github.sha }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEVAPICONTAINERAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n dev-api-container-app -g nonprod-backend --server bacibackend.azurecr.io --username  ${{ secrets.DEVAPICONTAINERAPP_REGISTRY_USERNAME }} --password ${{ secrets.DEVAPICONTAINERAPP_REGISTRY_PASSWORD }}
            az containerapp update -n dev-api-container-app -g nonprod-backend --image bacibackend.azurecr.io/backend-dev:${{ github.sha }}
