# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - baci-backend

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://bacibackend.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_0b385c72f30242bdb695d78d992c0a18 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_26cf0cc19fd34539a9160b2a3f68b817 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: bacibackend.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0b385c72f30242bdb695d78d992c0a18 }}/backend-dev:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'baci-backend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6bc9d074020345fc9c2e1d3c42356e0b }}
        images: 'bacibackend.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0b385c72f30242bdb695d78d992c0a18 }}/backend-dev:${{ github.sha }}'